// Generated by gencpp from file acroba_workshop_sigma/LeadResult.msg
// DO NOT EDIT!


#ifndef ACROBA_WORKSHOP_SIGMA_MESSAGE_LEADRESULT_H
#define ACROBA_WORKSHOP_SIGMA_MESSAGE_LEADRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acroba_workshop_sigma
{
template <class ContainerAllocator>
struct LeadResult_
{
  typedef LeadResult_<ContainerAllocator> Type;

  LeadResult_()
    {
    }
  LeadResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> const> ConstPtr;

}; // struct LeadResult_

typedef ::acroba_workshop_sigma::LeadResult_<std::allocator<void> > LeadResult;

typedef boost::shared_ptr< ::acroba_workshop_sigma::LeadResult > LeadResultPtr;
typedef boost::shared_ptr< ::acroba_workshop_sigma::LeadResult const> LeadResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace acroba_workshop_sigma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::acroba_workshop_sigma::LeadResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acroba_workshop_sigma/LeadResult";
  }

  static const char* value(const ::acroba_workshop_sigma::LeadResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Define result's message\n"
;
  }

  static const char* value(const ::acroba_workshop_sigma::LeadResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LeadResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acroba_workshop_sigma::LeadResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::acroba_workshop_sigma::LeadResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ACROBA_WORKSHOP_SIGMA_MESSAGE_LEADRESULT_H
