// Generated by gencpp from file acroba_workshop_sigma/PatrolSkillResult.msg
// DO NOT EDIT!


#ifndef ACROBA_WORKSHOP_SIGMA_MESSAGE_PATROLSKILLRESULT_H
#define ACROBA_WORKSHOP_SIGMA_MESSAGE_PATROLSKILLRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acroba_workshop_sigma
{
template <class ContainerAllocator>
struct PatrolSkillResult_
{
  typedef PatrolSkillResult_<ContainerAllocator> Type;

  PatrolSkillResult_()
    : success(false)  {
    }
  PatrolSkillResult_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolSkillResult_

typedef ::acroba_workshop_sigma::PatrolSkillResult_<std::allocator<void> > PatrolSkillResult;

typedef boost::shared_ptr< ::acroba_workshop_sigma::PatrolSkillResult > PatrolSkillResultPtr;
typedef boost::shared_ptr< ::acroba_workshop_sigma::PatrolSkillResult const> PatrolSkillResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator1> & lhs, const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator1> & lhs, const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acroba_workshop_sigma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acroba_workshop_sigma/PatrolSkillResult";
  }

  static const char* value(const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"bool success\n"
;
  }

  static const char* value(const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolSkillResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acroba_workshop_sigma::PatrolSkillResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACROBA_WORKSHOP_SIGMA_MESSAGE_PATROLSKILLRESULT_H
