// Generated by gencpp from file acroba_workshop_sigma/PatrolGoal.msg
// DO NOT EDIT!


#ifndef ACROBA_WORKSHOP_SIGMA_MESSAGE_PATROLGOAL_H
#define ACROBA_WORKSHOP_SIGMA_MESSAGE_PATROLGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace acroba_workshop_sigma
{
template <class ContainerAllocator>
struct PatrolGoal_
{
  typedef PatrolGoal_<ContainerAllocator> Type;

  PatrolGoal_()
    : turtle_name()
    , speed_move(0.0)
    , distance(0.0)
    , isForward(false)
    , speed_rotate(0.0)
    , degrees(0.0)
    , isClockwise(false)  {
    }
  PatrolGoal_(const ContainerAllocator& _alloc)
    : turtle_name(_alloc)
    , speed_move(0.0)
    , distance(0.0)
    , isForward(false)
    , speed_rotate(0.0)
    , degrees(0.0)
    , isClockwise(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _turtle_name_type;
  _turtle_name_type turtle_name;

   typedef float _speed_move_type;
  _speed_move_type speed_move;

   typedef float _distance_type;
  _distance_type distance;

   typedef uint8_t _isForward_type;
  _isForward_type isForward;

   typedef float _speed_rotate_type;
  _speed_rotate_type speed_rotate;

   typedef float _degrees_type;
  _degrees_type degrees;

   typedef uint8_t _isClockwise_type;
  _isClockwise_type isClockwise;





  typedef boost::shared_ptr< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PatrolGoal_

typedef ::acroba_workshop_sigma::PatrolGoal_<std::allocator<void> > PatrolGoal;

typedef boost::shared_ptr< ::acroba_workshop_sigma::PatrolGoal > PatrolGoalPtr;
typedef boost::shared_ptr< ::acroba_workshop_sigma::PatrolGoal const> PatrolGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator1> & lhs, const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator2> & rhs)
{
  return lhs.turtle_name == rhs.turtle_name &&
    lhs.speed_move == rhs.speed_move &&
    lhs.distance == rhs.distance &&
    lhs.isForward == rhs.isForward &&
    lhs.speed_rotate == rhs.speed_rotate &&
    lhs.degrees == rhs.degrees &&
    lhs.isClockwise == rhs.isClockwise;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator1> & lhs, const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace acroba_workshop_sigma

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28f8b262499b05e0030c6536920d8221";
  }

  static const char* value(const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28f8b262499b05e0ULL;
  static const uint64_t static_value2 = 0x030c6536920d8221ULL;
};

template<class ContainerAllocator>
struct DataType< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acroba_workshop_sigma/PatrolGoal";
  }

  static const char* value(const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define goal's message\n"
"string turtle_name\n"
"float32 speed_move\n"
"float32 distance\n"
"bool isForward\n"
"float32 speed_rotate\n"
"float32 degrees\n"
"bool isClockwise\n"
;
  }

  static const char* value(const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.turtle_name);
      stream.next(m.speed_move);
      stream.next(m.distance);
      stream.next(m.isForward);
      stream.next(m.speed_rotate);
      stream.next(m.degrees);
      stream.next(m.isClockwise);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PatrolGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::acroba_workshop_sigma::PatrolGoal_<ContainerAllocator>& v)
  {
    s << indent << "turtle_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.turtle_name);
    s << indent << "speed_move: ";
    Printer<float>::stream(s, indent + "  ", v.speed_move);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "isForward: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isForward);
    s << indent << "speed_rotate: ";
    Printer<float>::stream(s, indent + "  ", v.speed_rotate);
    s << indent << "degrees: ";
    Printer<float>::stream(s, indent + "  ", v.degrees);
    s << indent << "isClockwise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isClockwise);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACROBA_WORKSHOP_SIGMA_MESSAGE_PATROLGOAL_H
