
(cl:in-package :asdf)

(defsystem "acroba_workshop_sigma-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :actionlib_msgs-msg
               :std_msgs-msg
               :turtlesim-msg
)
  :components ((:file "_package")
    (:file "Move2Action" :depends-on ("_package_Move2Action"))
    (:file "_package_Move2Action" :depends-on ("_package"))
    (:file "Move2ActionFeedback" :depends-on ("_package_Move2ActionFeedback"))
    (:file "_package_Move2ActionFeedback" :depends-on ("_package"))
    (:file "Move2ActionGoal" :depends-on ("_package_Move2ActionGoal"))
    (:file "_package_Move2ActionGoal" :depends-on ("_package"))
    (:file "Move2ActionResult" :depends-on ("_package_Move2ActionResult"))
    (:file "_package_Move2ActionResult" :depends-on ("_package"))
    (:file "Move2Feedback" :depends-on ("_package_Move2Feedback"))
    (:file "_package_Move2Feedback" :depends-on ("_package"))
    (:file "Move2Goal" :depends-on ("_package_Move2Goal"))
    (:file "_package_Move2Goal" :depends-on ("_package"))
    (:file "Move2Result" :depends-on ("_package_Move2Result"))
    (:file "_package_Move2Result" :depends-on ("_package"))
    (:file "MoveAction" :depends-on ("_package_MoveAction"))
    (:file "_package_MoveAction" :depends-on ("_package"))
    (:file "MoveActionFeedback" :depends-on ("_package_MoveActionFeedback"))
    (:file "_package_MoveActionFeedback" :depends-on ("_package"))
    (:file "MoveActionGoal" :depends-on ("_package_MoveActionGoal"))
    (:file "_package_MoveActionGoal" :depends-on ("_package"))
    (:file "MoveActionResult" :depends-on ("_package_MoveActionResult"))
    (:file "_package_MoveActionResult" :depends-on ("_package"))
    (:file "MoveFeedback" :depends-on ("_package_MoveFeedback"))
    (:file "_package_MoveFeedback" :depends-on ("_package"))
    (:file "MoveGoal" :depends-on ("_package_MoveGoal"))
    (:file "_package_MoveGoal" :depends-on ("_package"))
    (:file "MoveResult" :depends-on ("_package_MoveResult"))
    (:file "_package_MoveResult" :depends-on ("_package"))
    (:file "PatrolSkillAction" :depends-on ("_package_PatrolSkillAction"))
    (:file "_package_PatrolSkillAction" :depends-on ("_package"))
    (:file "PatrolSkillActionFeedback" :depends-on ("_package_PatrolSkillActionFeedback"))
    (:file "_package_PatrolSkillActionFeedback" :depends-on ("_package"))
    (:file "PatrolSkillActionGoal" :depends-on ("_package_PatrolSkillActionGoal"))
    (:file "_package_PatrolSkillActionGoal" :depends-on ("_package"))
    (:file "PatrolSkillActionResult" :depends-on ("_package_PatrolSkillActionResult"))
    (:file "_package_PatrolSkillActionResult" :depends-on ("_package"))
    (:file "PatrolSkillFeedback" :depends-on ("_package_PatrolSkillFeedback"))
    (:file "_package_PatrolSkillFeedback" :depends-on ("_package"))
    (:file "PatrolSkillGoal" :depends-on ("_package_PatrolSkillGoal"))
    (:file "_package_PatrolSkillGoal" :depends-on ("_package"))
    (:file "PatrolSkillResult" :depends-on ("_package_PatrolSkillResult"))
    (:file "_package_PatrolSkillResult" :depends-on ("_package"))
    (:file "rotateAction" :depends-on ("_package_rotateAction"))
    (:file "_package_rotateAction" :depends-on ("_package"))
    (:file "rotateActionFeedback" :depends-on ("_package_rotateActionFeedback"))
    (:file "_package_rotateActionFeedback" :depends-on ("_package"))
    (:file "rotateActionGoal" :depends-on ("_package_rotateActionGoal"))
    (:file "_package_rotateActionGoal" :depends-on ("_package"))
    (:file "rotateActionResult" :depends-on ("_package_rotateActionResult"))
    (:file "_package_rotateActionResult" :depends-on ("_package"))
    (:file "rotateFeedback" :depends-on ("_package_rotateFeedback"))
    (:file "_package_rotateFeedback" :depends-on ("_package"))
    (:file "rotateGoal" :depends-on ("_package_rotateGoal"))
    (:file "_package_rotateGoal" :depends-on ("_package"))
    (:file "rotateResult" :depends-on ("_package_rotateResult"))
    (:file "_package_rotateResult" :depends-on ("_package"))
  ))