; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude FollowFeedback.msg.html

(cl:defclass <FollowFeedback> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type turtlesim-msg:Pose
    :initform (cl:make-instance 'turtlesim-msg:Pose)))
)

(cl:defclass FollowFeedback (<FollowFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<FollowFeedback> is deprecated: use acroba_workshop_sigma-msg:FollowFeedback instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <FollowFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acroba_workshop_sigma-msg:pose-val is deprecated.  Use acroba_workshop_sigma-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowFeedback>) ostream)
  "Serializes a message object of type '<FollowFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowFeedback>) istream)
  "Deserializes a message object of type '<FollowFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowFeedback>)))
  "Returns string type for a message object of type '<FollowFeedback>"
  "acroba_workshop_sigma/FollowFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowFeedback)))
  "Returns string type for a message object of type 'FollowFeedback"
  "acroba_workshop_sigma/FollowFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowFeedback>)))
  "Returns md5sum for a message object of type '<FollowFeedback>"
  "582239f3e6c49527a893bd9673357b39")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowFeedback)))
  "Returns md5sum for a message object of type 'FollowFeedback"
  "582239f3e6c49527a893bd9673357b39")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowFeedback>)))
  "Returns full string definition for message of type '<FollowFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define feedback's message~%turtlesim/Pose pose~%~%~%~%================================================================================~%MSG: turtlesim/Pose~%float32 x~%float32 y~%float32 theta~%~%float32 linear_velocity~%float32 angular_velocity~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowFeedback)))
  "Returns full string definition for message of type 'FollowFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define feedback's message~%turtlesim/Pose pose~%~%~%~%================================================================================~%MSG: turtlesim/Pose~%float32 x~%float32 y~%float32 theta~%~%float32 linear_velocity~%float32 angular_velocity~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowFeedback
    (cl:cons ':pose (pose msg))
))
