; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude FollowResult.msg.html

(cl:defclass <FollowResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FollowResult (<FollowResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<FollowResult> is deprecated: use acroba_workshop_sigma-msg:FollowResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowResult>) ostream)
  "Serializes a message object of type '<FollowResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowResult>) istream)
  "Deserializes a message object of type '<FollowResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowResult>)))
  "Returns string type for a message object of type '<FollowResult>"
  "acroba_workshop_sigma/FollowResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowResult)))
  "Returns string type for a message object of type 'FollowResult"
  "acroba_workshop_sigma/FollowResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowResult>)))
  "Returns md5sum for a message object of type '<FollowResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowResult)))
  "Returns md5sum for a message object of type 'FollowResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowResult>)))
  "Returns full string definition for message of type '<FollowResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowResult)))
  "Returns full string definition for message of type 'FollowResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowResult
))
