; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude LeadResult.msg.html

(cl:defclass <LeadResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LeadResult (<LeadResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LeadResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LeadResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<LeadResult> is deprecated: use acroba_workshop_sigma-msg:LeadResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LeadResult>) ostream)
  "Serializes a message object of type '<LeadResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LeadResult>) istream)
  "Deserializes a message object of type '<LeadResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LeadResult>)))
  "Returns string type for a message object of type '<LeadResult>"
  "acroba_workshop_sigma/LeadResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LeadResult)))
  "Returns string type for a message object of type 'LeadResult"
  "acroba_workshop_sigma/LeadResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LeadResult>)))
  "Returns md5sum for a message object of type '<LeadResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LeadResult)))
  "Returns md5sum for a message object of type 'LeadResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LeadResult>)))
  "Returns full string definition for message of type '<LeadResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LeadResult)))
  "Returns full string definition for message of type 'LeadResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LeadResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LeadResult>))
  "Converts a ROS message object to a list"
  (cl:list 'LeadResult
))
