; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude Move2Feedback.msg.html

(cl:defclass <Move2Feedback> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type turtlesim-msg:Pose
    :initform (cl:make-instance 'turtlesim-msg:Pose)))
)

(cl:defclass Move2Feedback (<Move2Feedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Move2Feedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Move2Feedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<Move2Feedback> is deprecated: use acroba_workshop_sigma-msg:Move2Feedback instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <Move2Feedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acroba_workshop_sigma-msg:pose-val is deprecated.  Use acroba_workshop_sigma-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Move2Feedback>) ostream)
  "Serializes a message object of type '<Move2Feedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Move2Feedback>) istream)
  "Deserializes a message object of type '<Move2Feedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Move2Feedback>)))
  "Returns string type for a message object of type '<Move2Feedback>"
  "acroba_workshop_sigma/Move2Feedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Move2Feedback)))
  "Returns string type for a message object of type 'Move2Feedback"
  "acroba_workshop_sigma/Move2Feedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Move2Feedback>)))
  "Returns md5sum for a message object of type '<Move2Feedback>"
  "582239f3e6c49527a893bd9673357b39")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Move2Feedback)))
  "Returns md5sum for a message object of type 'Move2Feedback"
  "582239f3e6c49527a893bd9673357b39")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Move2Feedback>)))
  "Returns full string definition for message of type '<Move2Feedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define feedback's message~%turtlesim/Pose pose~%~%~%================================================================================~%MSG: turtlesim/Pose~%float32 x~%float32 y~%float32 theta~%~%float32 linear_velocity~%float32 angular_velocity~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Move2Feedback)))
  "Returns full string definition for message of type 'Move2Feedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define feedback's message~%turtlesim/Pose pose~%~%~%================================================================================~%MSG: turtlesim/Pose~%float32 x~%float32 y~%float32 theta~%~%float32 linear_velocity~%float32 angular_velocity~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Move2Feedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Move2Feedback>))
  "Converts a ROS message object to a list"
  (cl:list 'Move2Feedback
    (cl:cons ':pose (pose msg))
))
