; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude Move2Result.msg.html

(cl:defclass <Move2Result> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass Move2Result (<Move2Result>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Move2Result>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Move2Result)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<Move2Result> is deprecated: use acroba_workshop_sigma-msg:Move2Result instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Move2Result>) ostream)
  "Serializes a message object of type '<Move2Result>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Move2Result>) istream)
  "Deserializes a message object of type '<Move2Result>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Move2Result>)))
  "Returns string type for a message object of type '<Move2Result>"
  "acroba_workshop_sigma/Move2Result")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Move2Result)))
  "Returns string type for a message object of type 'Move2Result"
  "acroba_workshop_sigma/Move2Result")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Move2Result>)))
  "Returns md5sum for a message object of type '<Move2Result>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Move2Result)))
  "Returns md5sum for a message object of type 'Move2Result"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Move2Result>)))
  "Returns full string definition for message of type '<Move2Result>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Move2Result)))
  "Returns full string definition for message of type 'Move2Result"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Move2Result>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Move2Result>))
  "Converts a ROS message object to a list"
  (cl:list 'Move2Result
))
