; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude PatrolSkillActionGoal.msg.html

(cl:defclass <PatrolSkillActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type acroba_workshop_sigma-msg:PatrolSkillGoal
    :initform (cl:make-instance 'acroba_workshop_sigma-msg:PatrolSkillGoal)))
)

(cl:defclass PatrolSkillActionGoal (<PatrolSkillActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PatrolSkillActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PatrolSkillActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<PatrolSkillActionGoal> is deprecated: use acroba_workshop_sigma-msg:PatrolSkillActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <PatrolSkillActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acroba_workshop_sigma-msg:header-val is deprecated.  Use acroba_workshop_sigma-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <PatrolSkillActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acroba_workshop_sigma-msg:goal_id-val is deprecated.  Use acroba_workshop_sigma-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <PatrolSkillActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acroba_workshop_sigma-msg:goal-val is deprecated.  Use acroba_workshop_sigma-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PatrolSkillActionGoal>) ostream)
  "Serializes a message object of type '<PatrolSkillActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PatrolSkillActionGoal>) istream)
  "Deserializes a message object of type '<PatrolSkillActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PatrolSkillActionGoal>)))
  "Returns string type for a message object of type '<PatrolSkillActionGoal>"
  "acroba_workshop_sigma/PatrolSkillActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PatrolSkillActionGoal)))
  "Returns string type for a message object of type 'PatrolSkillActionGoal"
  "acroba_workshop_sigma/PatrolSkillActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PatrolSkillActionGoal>)))
  "Returns md5sum for a message object of type '<PatrolSkillActionGoal>"
  "f5eb5652d69e379193b91f6a42940be5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PatrolSkillActionGoal)))
  "Returns md5sum for a message object of type 'PatrolSkillActionGoal"
  "f5eb5652d69e379193b91f6a42940be5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PatrolSkillActionGoal>)))
  "Returns full string definition for message of type '<PatrolSkillActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%PatrolSkillGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: acroba_workshop_sigma/PatrolSkillGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# The action goal for creating a rectangle~%string turtle_name~%float32 move_distance~%float32 move_speed~%float32 rotate_angle~%int32 repetitions~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PatrolSkillActionGoal)))
  "Returns full string definition for message of type 'PatrolSkillActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%PatrolSkillGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: acroba_workshop_sigma/PatrolSkillGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# The action goal for creating a rectangle~%string turtle_name~%float32 move_distance~%float32 move_speed~%float32 rotate_angle~%int32 repetitions~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PatrolSkillActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PatrolSkillActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PatrolSkillActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
