; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude PatrolSkillResult.msg.html

(cl:defclass <PatrolSkillResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass PatrolSkillResult (<PatrolSkillResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PatrolSkillResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PatrolSkillResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<PatrolSkillResult> is deprecated: use acroba_workshop_sigma-msg:PatrolSkillResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <PatrolSkillResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader acroba_workshop_sigma-msg:success-val is deprecated.  Use acroba_workshop_sigma-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PatrolSkillResult>) ostream)
  "Serializes a message object of type '<PatrolSkillResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PatrolSkillResult>) istream)
  "Deserializes a message object of type '<PatrolSkillResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PatrolSkillResult>)))
  "Returns string type for a message object of type '<PatrolSkillResult>"
  "acroba_workshop_sigma/PatrolSkillResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PatrolSkillResult)))
  "Returns string type for a message object of type 'PatrolSkillResult"
  "acroba_workshop_sigma/PatrolSkillResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PatrolSkillResult>)))
  "Returns md5sum for a message object of type '<PatrolSkillResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PatrolSkillResult)))
  "Returns md5sum for a message object of type 'PatrolSkillResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PatrolSkillResult>)))
  "Returns full string definition for message of type '<PatrolSkillResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PatrolSkillResult)))
  "Returns full string definition for message of type 'PatrolSkillResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PatrolSkillResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PatrolSkillResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PatrolSkillResult
    (cl:cons ':success (success msg))
))
