; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude PatrolResult.msg.html

(cl:defclass <PatrolResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PatrolResult (<PatrolResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PatrolResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PatrolResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<PatrolResult> is deprecated: use acroba_workshop_sigma-msg:PatrolResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PatrolResult>) ostream)
  "Serializes a message object of type '<PatrolResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PatrolResult>) istream)
  "Deserializes a message object of type '<PatrolResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PatrolResult>)))
  "Returns string type for a message object of type '<PatrolResult>"
  "acroba_workshop_sigma/PatrolResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PatrolResult)))
  "Returns string type for a message object of type 'PatrolResult"
  "acroba_workshop_sigma/PatrolResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PatrolResult>)))
  "Returns md5sum for a message object of type '<PatrolResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PatrolResult)))
  "Returns md5sum for a message object of type 'PatrolResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PatrolResult>)))
  "Returns full string definition for message of type '<PatrolResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PatrolResult)))
  "Returns full string definition for message of type 'PatrolResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PatrolResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PatrolResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PatrolResult
))
