; Auto-generated. Do not edit!


(cl:in-package acroba_workshop_sigma-msg)


;//! \htmlinclude rotateResult.msg.html

(cl:defclass <rotateResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass rotateResult (<rotateResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <rotateResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'rotateResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name acroba_workshop_sigma-msg:<rotateResult> is deprecated: use acroba_workshop_sigma-msg:rotateResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <rotateResult>) ostream)
  "Serializes a message object of type '<rotateResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <rotateResult>) istream)
  "Deserializes a message object of type '<rotateResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<rotateResult>)))
  "Returns string type for a message object of type '<rotateResult>"
  "acroba_workshop_sigma/rotateResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'rotateResult)))
  "Returns string type for a message object of type 'rotateResult"
  "acroba_workshop_sigma/rotateResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<rotateResult>)))
  "Returns md5sum for a message object of type '<rotateResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'rotateResult)))
  "Returns md5sum for a message object of type 'rotateResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<rotateResult>)))
  "Returns full string definition for message of type '<rotateResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'rotateResult)))
  "Returns full string definition for message of type 'rotateResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define result's message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <rotateResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <rotateResult>))
  "Converts a ROS message object to a list"
  (cl:list 'rotateResult
))
